# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338252d96237d4c73437456cc7df7884cb8560f9e92c0d2f5f4422dc9fc06d670a69837e2595fe7cef80a53419de376aa0384eb5a54f8a41396764c4b001cd52

test:
  secret_key_base: a43d7f3292e1af917a6712656f49b45d7b1913992f5df97c189554a635fec07757fac1b7d26ad2777399a3f2604370389941e30c21ccc0602c99385faab34326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
